[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
campusfi = "GdDRw2Z8wmnVndyNCDndk3AubLp8vrErAtqMFcBri8Nt"

[programs.localnet]
campusfi = "GdDRw2Z8wmnVndyNCDndk3AubLp8vrErAtqMFcBri8Nt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ".anchor/deploy-wallet.json"

[scripts]
test = "\"/mnt/c/Program Files/nodejs/node.exe\" --test tests/campusfi.test.js"
